import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/shared/Footer";
import ScrollProgressBar from "@/component/common/ScrollProgressBar";
import ChatWidget from "@/component/chat/ChatWidget";



export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased `}
      >
        <ScrollProgressBar />
        <ChatWidget />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
